### ISSUE TITLE
cannot import name 'LossRobustBIC' from 'ddm.models' 

### ISSUE THREAD

**Issue by hcp4715** [mwshinn/PyDDM#20]
Hi, there,

Thanks for sharing your package!
I am trying to run the code in the quick start guid (https://pyddm.readthedocs.io/en/latest/quickstart.html). When running `from ddm.models import LossRobustBIC`, I encountered an error:

`ImportError: cannot import name 'LossRobustBIC' from 'ddm.models' (/home/user/miniconda3/envs/pyddm/lib/python3.8/site-packages/ddm/models/__init__.py)`

Here is my system info:

```
{'commit_hash': '2922831ac',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': '/home/user/miniconda3/envs/pyddm/lib/python3.8/site-packages/IPython',
 'ipython_version': '7.15.0',
 'os_name': 'posix',
 'platform': 'Linux-5.4.0-37-generic-x86_64-with-glibc2.10',
 'sys_executable': '/home/hcp4715/miniconda3/envs/pyddm/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.8.3 (default, May 19 2020, 18:47:26) \n[GCC 7.3.0]'}
```
The modules imported:

```
backcall==0.2.0
certifi==2020.4.5.2
cycler==0.10.0
decorator==4.4.2
entrypoints==0.3
ipykernel==5.3.0
ipython @ file:///tmp/build/80754af9/ipython_1592348389743/work
ipython-genutils==0.2.0
jedi==0.17.0
jupyter-client==6.1.3
jupyter-core==4.6.3
kiwisolver==1.2.0
matplotlib @ file:///tmp/build/80754af9/matplotlib-base_1592406092505/work
mkl-fft==1.1.0
mkl-random==1.1.1
mkl-service==2.3.0
numpy==1.18.1
pandas==1.0.4
paranoid-scientist==0.2.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.5
ptyprocess==0.6.0
pyddm==0.3.0
Pygments==2.6.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
pyzmq==18.1.1
scipy==1.4.1
seaborn==0.10.1
sip==4.19.13
six==1.15.0
tornado==6.0.4
traitlets==4.3.3
wcwidth==0.2.4
```

**Comment by mwshinn** [comment]
Thanks for your bug report.  We are getting close to releasing a new version of PyDDM, and right now the documentation confusingly refers to the development version (i.e. installed straight from github) instead of the version you install via pip.  So there are two options:

- Install the development of PyDDM from github instead of the version on pip
- Use the documentation for the current stable version, which does not refer to LossRobustBIC, here: https://pyddm.readthedocs.io/en/stable/

I won't close this issue yet because it's obvious how confusing this is right now, so I will gradually update our links to refer to the sable version of the documentation instead of the development version, and close it when I have done so.

**Comment by mwshinn** [comment]
I updated the links in the README (see referenced commit) and also changed the default version of the documentation on readthedocs.io, so that should take care of most of the links.  The links on pypi will update when we release the new version.

**Comment by hcp4715** [comment]
Hi, Max,
thanks for your quick response.
Looking forward to the new version.

**Comment by mwshinn** [comment]
I ended up just releasing the new version now: 0.4.0.  Enjoy!
