### ISSUE TITLE
corrupted condition numbers

### ISSUE THREAD

**Issue by ntardiff** [mwshinn/PyDDM#22]
The nested function pt() in Sample.from_pandas_dataframe() and Sample.from_numpy_array() casts condition numbers to int: ```arr = arr.astype(int)```. This casts them to np.int32, not to python built-in int, causing overflow for very long condition numbers. I'm guessing most people wouldn't encounter this problem, but I have a case where I needed to use very long condition numbers and stumbled upon the issue. I'm not sure if you could instead cast to np.int64 and still preserve functionality elsewhere? I also understand if this is too idiosyncratic a problem to address. In my case there is a 1-1 correspondence between the original condition number and the overflowed number, so I am able to recover my labels and can work around it.

**Comment by mwshinn** [comment]
Thanks for the bug report.  The latest commit should fix the problem.  It seems that numpy by default uses long type (from C), which is different on different platforms.  Notably, it seems to be int32 on Windows and int64 on other platforms.  Since it is not performance critical here, int64 should be fine.
