### ISSUE TITLE
Large number of warnings generated from Quickstart examples

### ISSUE THREAD

**Issue by mwaskom** [mwshinn/PyDDM#24]
Running the second example in the [Quick start guide](https://pyddm.readthedocs.io/en/stable/quickstart.html) (copying exactly, but adding `verbose=False`):

```python
from ddm import Model
from ddm.models import DriftConstant, NoiseConstant, BoundConstant, OverlayNonDecision
from ddm.functions import fit_adjust_model, display_model

model = Model(name='Simple model',
              drift=DriftConstant(drift=2.2),
              noise=NoiseConstant(noise=1.5),
              bound=BoundConstant(B=1.1),
              overlay=OverlayNonDecision(nondectime=.1),
              dx=.001, dt=.01, T_dur=2)
display_model(model)
sol = model.solve()

samp = sol.resample(1000)

from ddm import Fittable
from ddm.models import LossRobustBIC
from ddm.functions import fit_adjust_model
model_fit = Model(name='Simple model (fitted)',
                  drift=DriftConstant(drift=Fittable(minval=0, maxval=4)),
                  noise=NoiseConstant(noise=Fittable(minval=.5, maxval=4)),
                  bound=BoundConstant(B=1.1),
                  overlay=OverlayNonDecision(nondectime=Fittable(minval=0, maxval=1)),
                  dx=.001, dt=.01, T_dur=2)

fit_adjust_model(samp, model_fit,
                 fitting_method="differential_evolution",
                 lossfunction=LossRobustBIC, verbose=False)
```

Generates a large number (> 200) of warnings with the following text:

> Warning: infinite likelihood encountered. Please either use a Robust likelihood method (e.g. LossRobustLikelihood or LossRobustBIC) or even better use a mixture model (via an Overlay) which covers the full range of simulated times to avoid infinite negative log likelihood.  See the FAQs in the documentation for more information.

Two things about this are surprising:

1. It's unexpected to get so much negative feedback from running one of the provided examples
2. The warning instructes to use `LossRobustBIC`, but I believe that is what the code is doing.

Additionally, instead of using a simple `print()` here, would it make sense to use `warnings.warn` or `logging` with a `WARNING` level so it's easier to filter?

**Comment by mwshinn** [comment]
Thank you for the bug report!  I just pushed changes fixing a bug which was preventing LossRobustBIC from functioning as intended, so that should solve the main problem you reported.  Furthermore, you raise a good point in general about showing so much debugging output on the main examples, so I added "verbose=False" flags to the fit_adjust_model calls in the main documentation.  I agree with the more general point about switching from print statements to the logging module throughout PyDDM, and hopefully this is something I will get around to doing one of these days...
