### ISSUE TITLE
Solving fails using Gamma non-decision time distribution

### ISSUE THREAD

**Issue by ahyafil** [mwshinn/PyDDM#29]
Fails when solving for the pdf with a model that features Gamma distribution for non-decision time. here is the error message, and below minimal code to reproduce it:

ExitConditionsError: Ensures statement 'np.sum(return.corr) <= np.sum(solution.corr)' failed in OverlayNonDecisionGamma.apply
params: {'self': OverlayNonDecisionGamma(nondectime=0, shape=5, scale=0.1), 'solution': <ddm.solution.Solution object at 0x00000225BCB39048>, 'return': <ddm.solution.Solution object at 0x00000225BC032710>}
------

'''
from ddm import Model
from ddm.models import NoiseConstant, BoundConstant, OverlayChain, OverlayNonDecisionGamma, OverlayPoissonMixture
import ddm.models

class DriftCoherence(ddm.models.Drift):
    name = "Drift depends linearly on coherence"
    required_parameters = ["driftcoh"] # <-- Parameters we want to include in the model
    required_conditions = ["coh"] # <-- Task parameters ("conditions"). Should be the same name as in the sample.
    
    # We must always define the get_drift function, which is used to compute the instantaneous value of drift.
    def get_drift(self, conditions, **kwargs):
        return self.driftcoh * conditions['coh']
        
drift = 9.949529598148764 
B = 1 #0.9219102973749433
shape = 5 
scale = .1 
T_dur = 4        

NonDecisionModel = OverlayNonDecisionGamma(nondectime=0, shape=shape, scale=scale)

model = Model(name='drift varies with coherence and gamma nondecisiontime',

                drift = DriftCoherence(driftcoh=drift),
                 noise=NoiseConstant(noise=1),
                 bound=BoundConstant(B=B),
                 
                 overlay=OverlayChain(overlays=[NonDecisionModel,
                                                OverlayPoissonMixture(pmixturecoef=.02,
                                                                      rate=.5)]),
                 dx=.01, dt=.01, T_dur=T_dur)

model.T_dur = 20 # to ensure we have no (or very few) undecided trials

dd = {"coh":0.24628543028830302}
sol = model.solve(conditions = dd)
'''

**Comment by sammosummo** [comment]
Could you format your code properly (i.e., with fencing)? It will make it much easier for others to read/reproduce.

**Comment by ahyafil** [comment]
Hi Sam,

I'd be happy to do so, but I have no idea how to. I have searched for
fencing but couldn't find what it refers to.

best
Alex

Le ven. 19 mars 2021 à 17:59, Sam Mathias ***@***.***> a
écrit :

**Comment by sammosummo** [comment]
Code fences are a syntax element in [Markdown](https://guides.github.com/features/mastering-markdown/).

Basically, put ` ``` ` on the lines above and below your code block(s).

**Comment by mwshinn** [comment]
Don't worry about it Alex, I can understand what you mean. :)

**Comment by sammosummo** [comment]
Sometimes GitHub issues are useful for users as well as the developer. For example, I am currently trying to debug an issue and wanted to look at previous issues before posting a new one. In this particular case the definition of `model` is difficult to read because it's really long, contains multiple nested definitions and the indentation is off.  Below I changed ` ''' ` to ` ``` ` so that I at least can see what's going on more clearly.

```python
from ddm import Model
from ddm.models import NoiseConstant, BoundConstant, OverlayChain, OverlayNonDecisionGamma, OverlayPoissonMixture
import ddm.models

class DriftCoherence(ddm.models.Drift):
name = "Drift depends linearly on coherence"
required_parameters = ["driftcoh"] # <-- Parameters we want to include in the model
required_conditions = ["coh"] # <-- Task parameters ("conditions"). Should be the same name as in the sample.

# We must always define the get_drift function, which is used to compute the instantaneous value of drift.
def get_drift(self, conditions, **kwargs):
    return self.driftcoh * conditions['coh']
drift = 9.949529598148764
B = 1 #0.9219102973749433
shape = 5
scale = .1
T_dur = 4

NonDecisionModel = OverlayNonDecisionGamma(nondectime=0, shape=shape, scale=scale)

model = Model(name='drift varies with coherence and gamma nondecisiontime',

            drift = DriftCoherence(driftcoh=drift),
             noise=NoiseConstant(noise=1),
             bound=BoundConstant(B=B),
             
             overlay=OverlayChain(overlays=[NonDecisionModel,
                                            OverlayPoissonMixture(pmixturecoef=.02,
                                                                  rate=.5)]),
             dx=.01, dt=.01, T_dur=T_dur)
model.T_dur = 20 # to ensure we have no (or very few) undecided trials

dd = {"coh":0.24628543028830302}
sol = model.solve(conditions = dd)
```

And the error:

```
ExitConditionsError: Ensures statement 'np.sum(return.corr) <= np.sum(solution.corr)' failed in OverlayNonDecisionGamma.apply
params: {'self': OverlayNonDecisionGamma(nondectime=0, shape=5, scale=0.1), 'solution': <ddm.solution.Solution object at 0x00000225BCB39048>, 'return': <ddm.solution.Solution object at 0x00000225BC032710>}
```
