### ISSUE TITLE
GUI doesn't display histograms of different conditions and Realtime appears to have no effect

### ISSUE THREAD

**Issue by sammosummo** [mwshinn/PyDDM#30]
Python 3.8.8
PyDDM 0.5.1
Matplotlib 3.3.4

When the GUI is launched with `ddm.plot.model_gui`  I get this:

<img width="1021" alt="Screen Shot 2021-03-24 at 3 36 28 PM" src="https://user-images.githubusercontent.com/9464950/112372876-b98e9d80-8cb6-11eb-8ae7-a98000f75458.png">

I assume that clicking any radio button on the left-hand side besides `All` then clicking `Update` is supposed to show the histogram of data belonging to that condition, not the histogram of the entire dataset, but the histogram never updates irrespective of the radio button.

Moreover, the `Real-time` checkbox doesn't appear to be functional. I still have to click `Update` to see differences in the curve when moving the sliders on the right-hand side. The sliders themselves, `Update ` and `Reset` and  work as expected.

**Comment by mwshinn** [comment]
Thank you for the bug report.

Sometimes this problem occurs if the model GUI has previously been run, crashes, and then is run a second time.  Does this occur with a fresh Python session?

So that I can properly diagnose the problem, could you please send the full console output when this bug occurs, as well as a minimal working example to reproduce this bug?  Thanks!

**Comment by sammosummo** [comment]
Hmm, so my MWE actually works correctly ... not sure why it doesn't work in the context of my larger script. I will explore and get back to you. Probably best to leave the issue open until I isolate the bug.

**Comment by mwshinn** [comment]
I am closing this for now.  Please submit a new bug report if you find the bug.
