### ISSUE TITLE
Can `Overlay`s depend on conditions?

### ISSUE THREAD

**Issue by sammosummo** [mwshinn/PyDDM#32]
I have a model where the drift rate, noise, and non-decision time depend on conditions. The drift rate is equal to the condition value `delta`. This is easy to implement:

```python
class Drift(ddm.models.Drift):
    name = "drift rate depends on delta"
    required_parameters = []
    required_conditions = ["delta"]

    def get_drift(self, conditions, **kwargs):
        return conditions["delta"]
```

There are two sources of noise, one is a free parameter and another is proportional to the condition value `isi`. This again is not difficult:

```python
class Noise(ddm.models.Noise):
    name = "noise contains two variance components, one depends on the isi"
    required_parameters = ["s", "d"]
    required_conditions = ["isi"]

    def get_noise(self, conditions, **kwargs):
        return np.sqrt(2 * np.power(self.s, 2) + self.d * (conditions["isi"] + 0.1))
```

However I can't allow non-decision time to depend upon conditions because there is no `get_nodectime` method to overwrite. The following doesn't work:

```python
class NonDecision(ddm.models.OverlayNonDecision):
    name = "NonDecision is a flat amount plus isi"
    required_parameters = ["ndt"]
    required_conditions = ["isi"]

    def get_nondectime(self, conditions, **kwargs):
        return self.ndt + conditions["isi"]
```

Digging into the source code, `ddm.models.Drift` and `ddm.models.Noise` are subclasses of `Dependence` whereas  `ddm.models.OverlayNonDecision` is a subclass of `Overlay` (a subclass of `Dependence` itself).

Is there a reason why `Overlay`s don't have `get_{x}` methods? Is there some way to make them dependent on conditions?

**Comment by mwshinn** [comment]
Thank you for you bug report!

The Overlay methods are more general than just non-decision time.  They make any kind of post-simulation modification to the RT distributions.

The OverlayNonDecision class is a single instance of Overlay.  It is not necessarily made to be subclassed.  Currently, to make non-decision time depend on parameters, you need to subclass Overlay, and modify the "apply" method, which is the main method of the Overlay class, analogous to the "get_xxx" methods of the other model components.  You may also choose to implement the "apply_trajectory" method if you would like to do single trial trajectories instead of Fokker-Planck - this is present because modifying a distribution does not make sense on a single trial level, and these two perspectives cannot be reconciled by a single function.

However, I see why it is more useful to allow subclassing of OverlayNonDecision.  I am turning this ticket into a feature request to make it easier to subclass the existing OverlayNonDecision class.  In the meantime, you might want to see the following page from the Cookbook, which will give you a place to start in implementing this:

**Comment by sammosummo** [comment]
This is doubly great, because I also wanted to try out whether contaminant RTs were dependent on conditions. Thanks!

**Comment by mwshinn** [comment]
Finally implemented this feature!  Subclass using something like:

```
class OverlayNonDecisionISI(pyddm.models.OverlayNonDecision):
    name = "condition_nondecision"
    required_parameters = ["ndt"]
    required_conditions = ["isi"]
    def get_nondecision_time(self, conditions):
        return conditions['isi']  + self.ndt
```
