### ISSUE TITLE
assertion error in BoundCollapsingExponential

### ISSUE THREAD

**Issue by odedwer** [mwshinn/PyDDM#34]
In bound.py line 127 it is asserted that tau is in Positive, yet the documentation states that increasing bounds can be achieved with negative tau.

**Comment by mwshinn** [comment]
Good catch, thanks for the bug report.  Do you have a need for exponentially increasing bounds?  I am inclined to change the documentation to make BoundCollapsingExponential just for decreasing bounds, because increasing bounds in general are extremely rare in the literature (with no obvious use case for exponentially increasing bounds that I can think of) but they have the potential to cause strange problems if used without extreme caution.  It would still be possible to use increasing bounds in general, just not exponentially increasing bounds with the built in model component.

**Comment by odedwer** [comment]
Thank you for the very quick reply! 
We are still in the exploratory stage of the GDDM, so not sure whether we need it or not. We have data with really fast errors and almost gaussian like RT distributions and found that increasing bounds (with a fixed version of the BoundCollapsingExponential class that allows increasing bounds) more resembles our data. Even if you choose not to allow it, it is quite simple to create a custom class that allows it, so no problems if you change the doc :)
And as a general question - you have created a great and versatile tool,  why not allow these options with the built-in default classes?

**Comment by mwshinn** [comment]
So basically, in the implementation of Fokker-Planck for solving this, we need to create a NxT matrix, where T is the number of timepoints (T_dur/dt) and N is the number of grid spacings (grid size / dx).  For increasing bounds, we need to set the grid size to be the size of the largest width of the bounds.  If I were using PyDDM for the first time, I would probably say, "Well I don't know if it is increasing bounds, I might as well try it," and then set my range for tau from -10 to 10 or something.  However, if you set it to -10, then on a subset of simulations, there will be errors running out of memory since exponentially increasing functions are unbounded, and this requires making a huge NxT matrix.  Additionally, the runtime will be terrible.  So then this error will occur only very seldom (when the fitting algorithm chooses a value close to -10 for tau), and cause confusion.  It is not obvious why a parameter range should enormously increase the simulation time.  Since there is no literature suggesting this would be useful, and it is easy enough to create a custom class which allows exponentially increasing bounds, I will change the documentation to forbid exponentially increasing bounds.

By the way, if the increase is bounded, then this problem doesn't occur, e.g., for bounds based on the Weibull CDF: https://pyddm.readthedocs.io/en/latest/cookbook/bounds.html#bound-weibull-cdf

**Comment by mwshinn** [comment]
Fixed in dbbdeb9799d67fd5f6297bba91361fde957c311b
