### ISSUE TITLE
Issue with defining bounds varying linearly with a column value

### ISSUE THREAD

**Issue by krabhi-brn** [mwshinn/PyDDM#42]
I am trying to define a bound that would vary linearly with a column 'b' in the dataset. The column 'b' contains value that is a function of z-scores of reaction-time data (included in the data frame named 'z'). However, the code shows error on running. Link to the dataframe: [https://drive.google.com/file/d/1O4Ea-oaqbPR626KvMASk2m5hV09fhoHl/view?usp=sharing](url)
I'm new to python and pyDDM, and any help is appreciated.
Below is how I defined the drift-rate and bound:
```import ddm
class DriftCoherence(ddm.models.Drift):
    name = "Drift depends linearly on coherence"
    required_parameters = ["driftcoh"] 
    required_conditions = ["coh_list"] 
    
    def get_drift(self, conditions, **kwargs):
        return self.driftcoh * conditions['coh_list']

class adaptBound(ddm.Bound):
    name = "adaptive bounds depends linearly on the bound calculated as a function of z scores of RT"
    required_parameters = ["mbound"]
    required_conditions = ["b"]
    
    def get_bound(self, conditions, **kwargs):
        return self.metabound * conditions['b']
```

Model construction and fitting go like this:

```
from ddm import Model, Fittable
from ddm.functions import fit_adjust_model, display_model
from ddm.models import NoiseConstant, OverlayChain, OverlayNonDecision, OverlayPoissonMixture, LossRobustBIC
model_adapt = Model(name='All participants data, drift varies with coherence',
                 drift=DriftCoherence(driftcoh=Fittable(minval=0, maxval=20)),
                 noise=NoiseConstant(noise=1),
                 bound=adaptBound(mbound=Fittable(minval=-4, maxval=4.5)),
                 overlay=OverlayChain(overlays=[OverlayNonDecision(nondectime=Fittable(minval=0, maxval=.4)),
                                                OverlayPoissonMixture(pmixturecoef=.02,
                                                                      rate=1)]),
                 dx=.001, dt=.01, T_dur=2)


fit_model_adapt = fit_adjust_model(sample=all_sample, model=model_adapt, fitting_method="differential_evolution", lossfunction=LossRobustBIC, verbose=False)
display_model(fit_model_adapt)
```

**Comment by mwshinn** [comment]
@krabhi-brn I'm not sure if you solved your problem yet, but it looks like you mistyped one of your variables: in get_bound, you wrote "metabound" instead of "mbound".  Otherwise it looks like it should be correct!

@anne-urai Yes, in PyDDM they can not only depend on them linearly, but also nonlinearly for any arbitrary function you can write in Python.  To make this a bit more clear, I updated a few places in the documentation (listed below) and also added these to the Cookbook.  Let me know know if this answers your question!

https://pyddm.readthedocs.io/en/latest/cookbook/driftnoise.html#moment-to-moment-observations
https://pyddm.readthedocs.io/en/latest/faqs.html#does-pyddm-allow-non-discrete-conditions

**Comment by anne-urai** [comment]
Thanks, very clear! Also tagging @jwdegee

**Comment by mwshinn** [comment]
Oh yes, I should have mentioned that before PyDDM officially supported this by passing tuples as conditions, @jwdegee came up with a creative workaround: https://pyddm.readthedocs.io/en/latest/cookbook/papers/degee2020.html
