### ISSUE TITLE
shinn2020 example colab notebook broken

### ISSUE THREAD

**Issue by yanivabir** [mwshinn/PyDDM#53]
Hi,

It seems that the code for visualizing the Shin2020 model is broken. 

The following error is given when trying to run the visualize cell:
```
ArgumentTypeError: Invalid argument type: solution=<ddm.solution.Solution object at 0x7f4ed67f5810> is not of type Generic(<class 'ddm.solution.Solution'>) in OverlayChain.apply
```

**Comment by mwshinn** [comment]
Thanks for the bug report.

Looks like this was caused by a recent change.  While I work on fixing it, as a solution, replace the line in the Jupyter notebook which starts "!pip" with the following:

`!pip -q install git+https://github.com/mwshinn/PyDDM@v0.5.2`

Make sure you do this before you run the first cell.  (You may have to click on "Show code" first.)

**Comment by mwshinn** [comment]
Should be working again, even without the workaround!

**Comment by yanivabir** [comment]
thanks!
