### ISSUE TITLE
Can we get Hessian matrix?

### ISSUE THREAD

**Issue by hauselin** [mwshinn/PyDDM#64]
Is it possible to get the Hessian matrix from fitted `pyddm` objects? 

```py
# how to get Hessian matrix from a model like this one (adapted from docs)?
fit_model_rs = fit_adjust_model(sample=roitman_sample, model=model_rs, fitting_method="basin")
```

Appreciate any help anyone can provide. Thanks!

**Comment by hauselin** [comment]
I've been using mostly differential evolution, and it definitely works very well. But the downside of using a non-gradient-based algorithm like differential evolution is it doesn't provide any measure of error (e.g., SD or SE) for the estimated parameters. But if we can somehow get the Hessian, we can then estimate the error. 

According to this [StackOverflow question](https://stackoverflow.com/questions/70108843/can-scipy-optimize-differential-evolution-compute-sd-or-se-of-estimated-paramete), one hack would be to use the estimates from differential evolution as initial values for a gradient-based algorithm that returns the Hessian. And that led me to my question. 

This is definitely not a feature request, but just curious about what's possible and what you think. Thanks again!

**Comment by mwshinn** [comment]
Aah, got it.

By default, differential evolution actually carries out gradient descent at the end ("polish").  But it looks like it doesn't only saves the jacobian, see: https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/optimize/_differentialevolution.py#L915

Unfortunately, though, the hessian can't capture parameter variability for global optimisation, since there could be multiple peaks in the landscape.  The hessian is more of a measure of sensitivity at the given location in parameter space.  So yes, you will get a number, but it won't necessarily be meaningful.

If you still want the hessian, you can certainly use finite differences as linked in the SO question.  If you would rather use the hessian estimated by gradient descent (which I don't recommend) you can make the following change to PyDDM:

Go to this line: https://github.com/mwshinn/PyDDM/blob/890ab4d78bc1ade3698f8d1e3bed568e4a109555/pyddm/functions.py#L373 and add the middle two lines in the following:

```
res = FitResult(method=(method if method is not None else "auto"),
        hess=(x_fit.hess if "hess" in x_fit.__dict__ else None),
        hess_inv=(x_fit.hess_inv if "hess_inv" in x_fit.__dict__ else None),
        fitting_method=fitting_method, loss=lf.name, value=x_fit.fun,
```

This will give you the hessian and/or inverse hessian if the optimisation routine supports it.  (This should be the case for "simple" only.)  You can access this FitResult object as `m.fitresult` for the fit model `m`.  Haven't tested this but it should work.  If you want the jacobian, you can do something similar.

I'm not going to implement this in PyDDM itself because it is not a good way to go about estimating parameter variability.  One way to estimate parameter variability is to just fit the model multiple times - it isn't a very good way, but it does capture the propensity to hit different peaks in the global optimisation.

**Comment by hauselin** [comment]
Thanks for explaining, Max! These details are all super relevant and helpful. Thanks again!
