### ISSUE TITLE
Invalid pdf in solve_numerical_cn()?

### ISSUE THREAD

**Issue by stefan-f-bucher** [mwshinn/PyDDM#7]
Estimating a model sometimes results in ReturnTypeErrors that appear to arise in solve_numerical_cn() from the pdf having negative entries.
Running a model (BoundConstant) with ICPointSourceCenter works fine, while running it with a custom ICPointSource (which literally copies the code for ICPointSourceCenter from the repo) leads to 
```
ReturnTypeError: Invalid return type of [  4.84549201e-22   4.37823329e-20   1.94597413e-18 ...,   0.00000000e+00
   0.00000000e+00   0.00000000e+00] in Solution.pdf_corr
```
for some (but not all!) parameters during the fitting procedure.

The reason is that has_analytic_solution() requires ic=ICPointSourceCenter, and solve_numerical_cn() seems to run into issues with the pdf having negative entries (the reason for which does not seem apparent from the code in the repo...).
1) What is the cause for these ReturnTypeErrors and how can they be avoided?
2) Is ICPointSourceCenter strictly necessary for an analytical solution, or could the condition be relaxed to a Dirac initial condition that allows for a bias to be estimated?

**Comment by mwshinn** [comment]
PyDDM is (by design) very sensitive about potential errors in model specifications and numerical parameters.  As a result, it throws errors whenever there is a negative value in a PDF, since a PDF by definition should not have negative values.  If you get this error, usually this means that your numerics are too coarse for the model (e.g. you need to decrease dx and dt).  However, it can also occur during the fitting procedure because fitting algorithms will try extreme values which need very small timesteps.
One proposed fix for this is to disable these checks during model fitting only.  This fix has the added benefit of substantially improving the runtime of the fitting procedure.
In addition to this fix, it would be useful to have a better error message for this particular problem.  These two together should fix this bug.
Regarding your second point, yes, ICPointSourceCenter is currently necessary for an analytic solution.

**Comment by mwshinn** [comment]
Please let me know if this commit fixes the bug.

**Comment by stefan-f-bucher** [comment]
This indeed solves the problem, thank you for the quick fix!
