### ISSUE TITLE
Estimate parameters for several within-subject conditions

### ISSUE THREAD

**Issue by tkononow** [mwshinn/PyDDM#97]
Thank you for putting together this great code!

My question is related to https://github.com/mwshinn/PyDDM/discussions/75, but I still did not find an answer over there.

I want to compare the model parameters under two conditions: drug and saline, coded as 0 and 1. I see in the tutorial that you can add conditions[] in get_drift(). However, I'm not sure how you retrieve the fitted parameters for both conditions in such a case.

And the second, more general question: To retrieve parameters for different conditions, would you use the method above or rather fit the model separately per subject and condition?

Best,
Tadeusz

### Discussed in https://github.com/mwshinn/PyDDM/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **sadegh1985** May  8, 2023</sup>
When we estimate parameters for several within-subject conditions (e.g., coherence levels in Roitman data) the output is an average (across condition) for all parameters. Is it possible to retrieve parameters for separate conditions in PyDDM. 

Bests,

Sadegh</div>

**Comment by mwshinn** [comment]
It depends on how you defined your model and your drift component.  You define the drift rate based on the function you define for get_drift, which can depend on parameters or conditions.  The fitting procedure will give you the parameters that were passed into get_drift.  The way you would like to analyse those fitted parameters up to you.

Also, since this isn't a bug, please next time put it in discussions instead of filing a bug report.
